- name: configure mysql
  hosts: db
  become: yes
  tasks:
    - name: Install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: start mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    # Check DB connection
    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: db.pdevops72.online
        filter: version

    - name: Install python packages
      ansible.builtin.pip:
        name:
          - PyMySQL
        executable: pip3.9


